language: objective-c
osx_image: xcode8.3
xcode_project: DDLogManager
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: DDLogManager
#xcode_sdk: iphonesimulator9.3

# env:
#   global: 
#    - FRAMEWORK_NAME=<THIS_IS_A_PLACEHOLDER_REPLACE_ME>

# before_install:
#   - brew update
  # - brew outdated carthage || brew upgrade carthage

# before_script:
#   # bootstrap the dependencies for the project
#   # you can remove if you don't have dependencies
# - carthage bootstrap

script:
  # macos
  - xcodebuild clean build  -project DDLogManager.xcodeproj -scheme DDLogManager -configuration Release CODE_SIGNING_REQUIRED=NO
  # iphoneos
  - xcodebuild clean build  -sdk iphoneos -project DDLogManager.xcodeproj -scheme DDLogManager -configuration Release CODE_SIGNING_REQUIRED=NO
  # watchos
  - xcodebuild clean build  -sdk watchos -project DDLogManager.xcodeproj -scheme DDLogManager -configuration Release CODE_SIGNING_REQUIRED=NO
  # appletvos
  - xcodebuild clean build  -sdk appletvos -project DDLogManager.xcodeproj -scheme DDLogManager -configuration Release CODE_SIGNING_REQUIRED=NO

# before_deploy:
#   - carthage build --no-skip-current
#   - carthage archive $FRAMEWORK_NAME